Repository WJ-Andriod/Tracky, pull requests merged in 2023-05, with the labels that each got.

#2 DSL 적용
  .gitignore
  .idea/deploymentTargetDropDown.xml
  .idea/git_toolbox_prj.xml
  .idea/gradle.xml
  README.md
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
Labels: refactor

#3 PR 자동화 스크립트 추가
  .github/pull_request_template.md
Labels: another

#4 컴파일 에러 해결
  app/build.gradle.kts
Labels: bug

#5 버전 카탈로그 추가
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: another

#7 의존성 버전 명시
  app/build.gradle.kts
  app/src/main/java/com/wj/tracky/MainActivity.kt
  app/src/main/java/com/wj/tracky/ui/theme/Shape.kt
  app/src/main/java/com/wj/tracky/ui/theme/Theme.kt
  app/src/main/java/com/wj/tracky/ui/theme/Type.kt
  gradle/libs.versions.toml
Labels: refactor

#9 ktlint, detekt 적용
  app/src/androidTest/java/com/wj/tracky/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wj/tracky/MainActivity.kt
  app/src/main/java/com/wj/tracky/ui/theme/Color.kt
  app/src/main/java/com/wj/tracky/ui/theme/Shape.kt
  app/src/main/java/com/wj/tracky/ui/theme/Theme.kt
  app/src/main/java/com/wj/tracky/ui/theme/Type.kt
  app/src/test/java/com/wj/tracky/ExampleUnitTest.kt
  build.gradle.kts
  config/baseline.xml
  config/detekt.yml
  gradle/libs.versions.toml
Labels: another
